# Generated by Django 4.0 on 2024-03-03 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TecDetailes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tecname', models.CharField(max_length=100)),
                ('Tecemail', models.EmailField(max_length=254)),
                ('Tecqulfication', models.CharField(max_length=100)),
                ('TecExperence', models.IntegerField()),
                ('Tecjoining', models.DateTimeField()),
                ('Tecvillage', models.CharField(max_length=100)),
                ('Tecphoto', models.ImageField(upload_to='media/')),
            ],
        ),
    ]
