# Generated by Django 4.0 on 2024-03-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tecdetailes',
            name='Tecpassword',
            field=models.CharField(default='swetha', max_length=100),
            preserve_default=False,
        ),
    ]
