# Generated by Django 4.0 on 2024-03-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registermodel',
            name='studentphno',
            field=models.IntegerField(),
        ),
    ]
